name: Ejecutar código Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest  # Usa una máquina virtual de Ubuntu

    steps:
    - name: Verificar repositorio
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Usar la versión de Python que prefieras

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar script Python
      run: |
        python script.py  # Reemplaza con tu script Python

