# .github/workflows/auth-proxy.yml
name: OAuth Proxy
on:
  workflow_dispatch:
    inputs:
      code:
        description: 'OAuth code'
        required: true
      state:
        description: 'State parameter'
        required: true

jobs:
  exchange-token:
    runs-on: ubuntu-latest
    steps:
      - name: Exchange code for token
        env:
          CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Accept: application/json" \
            -d "client_id=$CLIENT_ID" \
            -d "client_secret=$CLIENT_SECRET" \
            -d "code=${{ github.event.inputs.code }}" \
            https://github.com/login/oauth/access_token)
          
          echo "token=$(echo $RESPONSE | jq -r '.access_token')" >> $GITHUB_OUTPUT
          
      - name: Create token file
        run: echo "${{ steps.exchange-token.outputs.token }}" > token.txt
        
      - name: Upload token
        uses: actions/upload-artifact@v4
        with:
          name: auth-token
          path: token.txt
