name: Process Text
on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Text to process'
        required: true

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Process text
        run: |
          echo "${{ inputs.text }}" > input.txt
          python process.py input.txt > output.txt
          
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: output.txt
