name: Run Python AI Model

on:
  workflow_dispatch:
    inputs:
      input_value:
        description: 'Input text/file/link'
        required: true

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Optional: Update checkout to v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Optional: Update setup-python to v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install transformers torch

      - name: Run Python script
        run: |
          python ai_model.py "${{ github.event.inputs.input_value }}"

      - name: Save output as artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: ai-response
          path: output.txt  # Ensure your script writes output to this file
